package lotte.newdevps.exception.user;

import lotte.newdevps.exception.http.NotFoundException;

public class UserNotFoundException extends NotFoundException {
}
